services:
  backend:
    image: business-app-backend:latest
    container_name: business-app-backend
    build:
      context: ./business-app/backend
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    environment:
      - PORT=8085
    networks:
      - business-network

  frontend:
    image: business-app-frontend:latest
    container_name: business-app-frontend
    build:
      context: ./business-app/frontend
      dockerfile: Dockerfile
    ports:
      - "8084:80"
    depends_on:
      - backend
    networks:
      - business-network


networks:
  business-network:
    driver: bridge